# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3ac061d733c20985f8518de4f95bd54747b70b8acf9cb2cc767ea734cad106c27f34cf9626e1e20ab46bfb26e31927108c276b00b1d062a6841aa85fc9bd5ad8

test:
  secret_key_base: 81f000dbf496d47986ad26e091c2c112b24dae99ba4c7ff7e073946f2451ab85ea4e8f37835fee17c3e9c47cea5542e6496bf755826562ef95287516d74efbe7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
