# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)

Book.delete_all
Author.delete_all
User.delete_all

u = Author.create({name: 'J.R.R. Tolkien', dob:'1892-01-03', nationality:'British', awards:nil, image_url:'http://upload.wikimedia.org/wikipedia/commons/thumb/b/b4/Tolkien_1916.jpg/220px-Tolkien_1916.jpg', biography: 'Born on January 3, 1892, in Bloemfontein, South Africa, J.R.R. Tolkien settled in England as a child, going on to study at Exeter College. While teaching at Oxford University, he published the popular fantasy novels The Hobbit and the Lord of the Rings trilogy. The works have had a devoted international fan base and been adapted into award-winning blockbuster films. Tolkien died in 1973 at 81.'})
u.books.create(isbn:'0395177111', title: 'The Hobbit', genre: 'Fantasy', pages: 384, published_on: '1937-09-21', total_in_library: 3, image_cover_url: 'http://cdn.pastemagazine.com/www/system/images/photo_albums/hobbit-book-covers/large/photo_5653_0-6.jpg?1384968217', abstract: 'Bilbo Baggins is a hobbit who enjoys a comfortable, unambitious life, rarely traveling any farther than his pantry or cellar. But his contentment is disturbed when the wizard Gandalf and a company of dwarves arrive on his doorstep one day to whisk him away on an adventure. They have launched a plot to raid the treasure hoard guarded by Smaug the Magnificent, a large and very dangerous dragon. Bilbo reluctantly joins their quest, unaware that on his journey to the Lonely Mountain he will encounter both a magic ring and a frightening creature known as Gollum.')
u.books.create(isbn:'0618002235', title: 'The Two Towers', genre: 'Fantasy', pages: 416, published_on: '1951-11-11', total_in_library: 5, image_cover_url: 'http://tolkiengateway.net/w/images/thumb/7/74/The_Two_Towers_1st_edition.jpg/180px-The_Two_Towers_1st_edition.jpg', abstract: 'The Two Towers is the second volume of J. R. R. Tolkien''s high fantasy novel The Lord of the Rings. It is preceded by The Fellowship of the Ring and followed by The Return of the King.')
u.books.create(isbn:'0345339738', title: 'The Return of the King', genre: 'Fantasy', pages: 624, published_on: '1955-10-20', total_in_library: 9, image_cover_url: 'http://www.davidlouisedelman.com/wp-content/uploads/return-of-the-king-cover-1.jpg', abstract: 'The Return of the King is the third and final volume of J. R. R. Tolkien''s The Lord of the Rings, following The Fellowship of the Ring and The Two Towers. The story begins in the kingdom of Gondor, which is soon to be attacked by the Dark Lord Sauron. The human Ranger Aragorn sets out to find the lost army of the undead oathbreakers.')

u = Author.create({name: 'Ayn Rand', dob:'1905-02-02', nationality:'Russian', awards:'Prometheus Award – Hall of Fame, Atlas Shrugged, Anthem', image_url:'http://upload.wikimedia.org/wikipedia/en/thumb/3/32/Ayn_Rand1.jpg/220px-Ayn_Rand1.jpg', biography: 'Russian-born Ayn Rand published her first bestseller, The Fountainhead, in 1943. She followed up with Atlas Shrugged in 1957. Rand''s novels and nonfiction work are heavily influenced by and intended to promote her philosophy of objectivism, which holds that individual self-achievement is more important than tradition or altruism, a theory that is closely tied to laissez-faire capitalism.'})
u.books.create(isbn:'0451191145', title: 'Atlas Shrugged', genre: 'Fiction', pages: 1200, published_on: '1957-10-10', total_in_library: 3, image_cover_url: 'http://frontierruminations.files.wordpress.com/2013/02/atlas-pic.jpg', abstract: 'The book explores a dystopian, increasingly socialist, post-economic collapse United States where many of society''s wealthiest citizens refuse to pay skyrocketing taxes, reject new regulations and disappear, shutting down the country''s vital industries. The disappearances evoke the imagery of what would happen if the mythological Atlas refused to continue to hold up the sky. They are led by John Galt.')

u = Author.create({name: 'Neal Stephenson', dob:'1959-10-31', nationality:'American', awards:nil, image_url:'http://upload.wikimedia.org/wikipedia/commons/thumb/c/c2/Neal_Stephenson_2008_crop.jpg/220px-Neal_Stephenson_2008_crop.jpg', biography: 'Neal Town Stephenson (born October 31, 1959) is an American writer, known for his speculative fiction works, which have been variously categorized science fiction, historical fiction, maximalism, cyberpunk, and postcyberpunk. Stephenson explores areas such as mathematics, cryptography, philosophy, currency, and the history of science. He also writes non-fiction articles about technology in publications such as Wired Magazine, and has worked part-time as an advisor for Blue Origin, a company (funded by Jeff Bezos) developing a manned sub-orbital launch system.'})
u.books.create(isbn:'0060512806', title: 'Cryptonomicon', genre: 'Fiction', pages: 918, published_on: '1999-05-01', total_in_library: 13, image_cover_url: 'http://d.gr-assets.com/books/1327931476l/816.jpg', abstract: "Cryptonomicon is a 1999 novel by American author Neal Stephenson. The novel follows the exploits of two groups of people in two different time periods, presented in alternating chapters. The first group is World War II-era Allied codebreakers and tactical-deception operatives affiliated with the Government Code and Cypher School at Bletchley Park and disillusioned Axis military and intelligence figures whom they encounter. The second narrative is set in the late 1990s with descendants of the first narrative's characters employing cryptologic, telecom and computer technology to build an underground data haven in the fictional Sultanate of Kinakuta. Their goal is to facilitate anonymous Internet banking using electronic money and (later) digital gold currency, with a longer range objective to distribute Holocaust Education and Avoidance Pod (HEAP) media for instructing genocide-target populations on defensive warfare.")

User.where(name: "Kevin").first_or_create!(name: "Kevin", user_id: "00001", password_digest:"$2a$10$3V47S9AWryjxiDEln/ty6OFGkz08DFGc6LS0EDUde3F2jS4Lk4dk.", admin:"true")
User.where(name: "Liam").first_or_create!(name: "Liam", user_id: "UserLiam", password_digest:"$2a$10$fBjmGuOfiKGPstwsmhazNuKxuxaEvUrJ7GMc8D.4l5RFN4lt97iCm", admin:"true")
User.where(name: "Ruben").first_or_create!(name: "Ruben", user_id: "UserRuben", password_digest:"$2a$10$fBjmGuOfiKGPstwsmhazNuKxuxaEvUrJ7GMc8D.4l5RFN4lt97iCm", admin:"true")
# Author.where(name: 'Orson Scott Card').first_or_create!(name: 'Orson Scott Card', dob:'1951-08-24', nationality:'American', awards:'Hugo Award, Nebula Award', image_url: 'http://en.wikipedia.org/wiki/File:Orson_Scott_Card_at_BYU_Symposium_20080216_closeup.jpg')
# Author.where(name: 'William Shakespeare').first_or_create!(name: 'William Shakespeare', dob:'1564-04-26', nationality:'British', awards:nil, image_url:'http://en.wikipedia.org/wiki/File:Shakespeare.jpg' )
# Author.where(name: 'Daniel Suarez').first_or_create!(name: 'Daniel Suarez', dob:'1964-12-21', nationality:'American', awards:nil, image_url:'http://en.wikipedia.org/wiki/File:Daniel_Suarez_2014_(cropped).jpg' )
# Author.where(name: 'Neal Stephenson').first_or_create!(name: 'Neal Stephenson', dob:'1959-10-31', nationality:'American', awards:nil, image_url:'http://en.wikipedia.org/wiki/File:Neal_Stephenson_2008_crop.jpg' )

# Book.where(title: 'The Fellowship of the Ring').first_or_create!(title: 'The Fellowship of the Ring', author: 'J.R.R. Tolkien', pages: 531, price: 8.09, genre: 'Fantasy', published_on: '1954-07-29', image_file_name: 'FellowshipOfTheRing.jpg', abstract: 'The Fellowship of the Ring is the first of three volumes of the epic novel The Lord of the Rings by the English author J. R. R. Tolkien. It takes place in the fictional universe of Middle-earth. It was originally published on July 29, 1954 in the United Kingdom.')
# Book.where(title: 'The Two Towers').first_or_create!(title: 'The Two Towers', author: 'J.R.R. Tolkien', pages: 416, price: 8.09, genre: 'Fantasy', published_on: '1951-11-11', image_file_name: 'TheTwoTowers.jpg', abstract: "The Two Towers is the second volume of J. R. R. Tolkien's high fantasy novel The Lord of the Rings. It is preceded by The Fellowship of the Ring and followed by The Return of the King.")
# Book.where(title: 'The Return of the King').first_or_create!(title: 'The Return of the King', author: 'J.R.R. Tolkien', pages: 624, price: 8.09, genre: 'Fantasy', published_on: '1955-10-20', image_file_name: 'TheReturnOfTheKing.jpg', abstract: "The Return of the King is the third and final volume of J. R. R. Tolkien's The Lord of the Rings, following The Fellowship of the Ring and The Two Towers. The story begins in the kingdom of Gondor, which is soon to be attacked by the Dark Lord Sauron. The human Ranger Aragorn sets out to find the lost army of the undead oathbreakers.")

# Book.where(title: "Ender's Game").first_or_create!(title: "Ender's Game", author: 'Orson Scott Card', pages: 352, price: 4.83, genre: 'Sci-Fi', published_on: '1977-08-01', image_file_name: 'EndersGame.jpg', abstract: "Ender's Game is a military science fiction novel by American author Orson Scott Card. Set in Earth's future, the novel presents an imperiled mankind after two conflicts with the 'Buggers', an insectoid alien species. In preparation for an anticipated third invasion, children, including the novel's protagonist, Ender Wiggin, are trained at a very young age through increasingly difficult games including some in zero gravity, where Ender's tactical genius is revealed.")
# Book.where(title: 'Hamlet').first_or_create!(title: 'Hamlet', author: 'Shakespeare', pages: 342, price: 5.34, genre: 'Tragedy', published_on: '1603-01-01', image_file_name: 'Hamlet.jpg', abstract: "The Tragedy of Hamlet, Prince of Denmark is a tragedy written by William Shakespeare between 1599 and 1602. Set in the Kingdom of Denmark, the play dramatizes the revenge Prince Hamlet exacts on his uncle Claudius for murdering King Hamlet, who is Claudius's brother and Prince Hamlet's father, and then succeeding to the throne and taking as his wife Gertrude, the old king's widow and Prince Hamlet's mother. The play vividly portrays both true and feigned madness—from overwhelming grief to seething rage—and explores themes of treachery, revenge, incest, and moral corruption.")
# Book.where(title: 'Daemon').first_or_create!(title: 'Daemon', author: 'Daniel Suarez', pages: 444, price: 9.99, genre: 'Sci-Fi', published_on: '2006-12-01', image_file_name: 'Daemon.png', abstract: 'Soon after the death of Matthew A. Sobol from brain cancer, a computer daemon is activated. Its first mission: to kill anyone and anything that stands in its way. Detective Peter Sebeck is called in to investigate the death of two programmers who worked for a computer game manufacturer, CyberStorm Entertainment.')
# Book.where(title: 'Freedom™').first_or_create!(title: 'Freedom™', author: 'Daniel Suarez', pages: 416, price: 9.99, genre: 'Sci-Fi', published_on: '2010-01-07', image_file_name: 'FreedomTM.jpg', abstract: "Freedom™, the sequel to Daemon, is the second of a two-part novel by the author Daniel Suarez about a distributed, persistent computer application, known as The Daemon, that begins to change the real world after the original programmer's death.")
# Book.where(title: 'Snow Crash').first_or_create!(title: 'Snow Crash', author: 'Neal Stephenson', pages: 480, price: 9.96, genre: 'Fiction', published_on: '1992-06-01', image_file_name: 'SnowCrash.jpg', abstract: 'The book presents the Sumerian language as the firmware programming language for the brainstem, which is supposedly functioning as the BIOS for the human brain. According to characters in the book, the goddess Asherah is the personification of a linguistic virus, similar to a computer virus. The god Enki created a counter-program which he called a nam-shub that caused all of humanity to speak different languages as a protection against Asherah (a re-interpretation of the ancient Near Eastern story of the Tower of Babel).')
# Book.where(title: 'The Diamond Age').first_or_create!(title: 'The Diamond Age', author: 'Neal Stephenson', pages: 455, price: 9.99, genre: 'Fiction', published_on: '1998-08-27', image_file_name: 'TheDiamondAge.jpg', abstract: "The Diamond Age: Or, A Young Lady's Illustrated Primer is a postcyberpunk novel by Neal Stephenson. It is to some extent a science fiction bildungsroman or coming-of-age story, focused on a young girl named Nell, and set in a future world in which nanotechnology affects all aspects of life.")
# Book.where(title: 'Kill Decision').first_or_create!(title: 'Kill Decision', author: 'Daniel Suarez', pages: 512, price: 10.50, genre: 'Fiction', published_on: '2012-07-19', image_file_name: 'KillDecision.jpg', abstract: "Kill Decision is a science fiction novel by Daniel Suarez published in 2012. It deals with themes of espionage, artificial intelligence, and warfare using robots and drones. The story deals with the fictional scenario where insurgents have created automated drones that identify enemies and make the decision to kill them (the 'Kill Decision' ) without human intervention.")
# Book.where(title: 'Influx').first_or_create!(title: 'Influx', author: 'Daniel Suarez', pages: 416, price: 20.50, genre: 'Fiction', published_on: '2014-02-20', image_file_name: 'Influx.jpg', abstract: "Imagine that scientists and researchers have already achieved major technological breakthroughs that could transform billions of lives—but they've done so in a world where the open exchange of ideas is viewed as dangerous and major technological advances are carefully managed.")